
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 12 09:02:47 ART 2017
//----------------------------------------------------

package parserProgram;

/** CUP generated interface containing symbol constants. */
public interface symFaulty {
  /* terminals */
  public static final int LPARENT = 7;
  public static final int RPARENT = 8;
  public static final int LBRACKET = 11;
  public static final int ASTERISK = 4;
  public static final int PUT = 34;
  public static final int SLASH = 6;
  public static final int INTEGER = 38;
  public static final int CHANNEL = 33;
  public static final int INT = 24;
  public static final int INIT = 26;
  public static final int MINUS = 3;
  public static final int SEMICOLON = 13;
  public static final int AND = 20;
  public static final int LT = 22;
  public static final int OR = 19;
  public static final int BOOL = 25;
  public static final int COMMA = 18;
  public static final int GET = 35;
  public static final int PLUS = 2;
  public static final int MAIN = 32;
  public static final int EXCLAMATION = 23;
  public static final int ID = 41;
  public static final int PROCESS = 28;
  public static final int OF = 29;
  public static final int EOF = 0;
  public static final int RBRACKET = 12;
  public static final int EQUAL = 16;
  public static final int TRUE = 39;
  public static final int error = 1;
  public static final int DOUBLE_EQUAL = 17;
  public static final int GLOBAL = 36;
  public static final int COLON = 14;
  public static final int LBRACE = 9;
  public static final int ENUM = 37;
  public static final int POINT = 5;
  public static final int NORMATIVE = 27;
  public static final int RBRACE = 10;
  public static final int RIGHTARROW = 15;
  public static final int USES = 30;
  public static final int FALSE = 40;
  public static final int RUN = 31;
  public static final int GT = 21;
}

