
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 12 09:02:47 ART 2017
//----------------------------------------------------

package parserFormula;

/** CUP generated interface containing symbol constants. */
public interface symDCTL {
  /* terminals */
  public static final int FORALL = 3;
  public static final int RECOVERY = 6;
  public static final int SEMI = 17;
  public static final int LPAREN = 7;
  public static final int RPAREN = 8;
  public static final int AND = 19;
  public static final int OR = 20;
  public static final int IMPLIES = 15;
  public static final int UNTIL = 10;
  public static final int NEXT = 9;
  public static final int ID = 18;
  public static final int EOF = 0;
  public static final int IMPLIESTEMP = 16;
  public static final int TRUE = 12;
  public static final int error = 1;
  public static final int PERMISSION = 4;
  public static final int COMPARISON = 21;
  public static final int NEG = 14;
  public static final int WEAK = 11;
  public static final int EXIST = 2;
  public static final int FALSE = 13;
  public static final int OBLIGATION = 5;
}

